import streamlit as st
import requests

# Set page configuration
st.set_page_config(page_title="Product Insights", page_icon="🛍️", layout="wide")

# Backend Gateway Address (pointing to your local Gateway API)
API_BASE_URL = "http://localhost:8001"

# Custom Styling
st.markdown("""
    <style>
    .stExpander { border: 1px solid #e6e9ef; border-radius: 8px; margin-bottom: 10px; }
    .stAlert { border-radius: 8px; }
    </style>
""", unsafe_allow_html=True)

st.title("Product Review")
st.divider()

# Searchable Dropdown (Always at top)
product_options = [
    "B003VXFK44 (Coffee)",
    "B000G6RYNE (Kettle Chips)",
    "B000G6MBX2 (Medium Roast)",
    "B000ER6YO0 (Alternative Coffee)",
    "B002BCD2OG (Agave Nectar)",
    "B004NE2E9O (Sardines - Low Data)"
]

selected_item = st.selectbox(
    "Search Product Database:",
    options=product_options,
    index=None,
    placeholder="Type or select a product ID...",
)

if selected_item:
    item_id = selected_item.split(" ")[0]
    
    # --- FETCH DATA ---
    with st.spinner(f"Querying backend for {item_id}..."):
        try:
            response = requests.get(f"{API_BASE_URL}/items/{item_id}", timeout=10)
            if response.status_code == 200:
                data = response.json()
            else:
                st.error(f"⚠️ Backend returned error {response.status_code}")
                st.stop()
        except:
            st.error("🔌 Could not connect to backend server. (Server is currently down)")
            st.info("💡 Tip: Use 'python -m RAG.main' to start the backend.")
            st.stop()

    # --- RENDER DATA (SPLIT LAYOUT) ---
    if data.get("status") == "INSUFFICIENT_DATA":
        st.warning(f"⚠️ {data.get('message')}")
    else:
        # Create two columns: Left (Summary) and Right (Aspects)
        left_col, right_col = st.columns([1, 2], gap="large")

        with left_col:
            st.subheader("🆔 Product Identity")
            st.markdown(f"**ID:** `{item_id}`")
            
            st.subheader("📝 Executive Summary")
            st.info(data.get("summary", "No summary available."))
            
            # Additional metadata if available
            st.caption("Generated by RAG Insights Engine v1.0")

        with right_col:
            st.subheader("🎯 Insights by Aspect")
            
            aspects = data.get("top_aspects", [])
            for item in aspects:
                cat = item.get("category", "Mixed")
                # Sentiment Styling
                if cat == "Pro":
                    icon, label = "✅", "Pro"
                elif cat == "Con":
                    icon, label = "❌", "Con"
                elif cat == "Mixed":
                    icon, label = "⚖️", "Mixed"
                else:
                    icon, label = "⚠️", "Insufficient Data"

                # Dropdown List (Expander)
                with st.expander(f"{icon} {item['aspect']} ({label})"):
                    # Pro/Con columns inside the expander
                    p_col, c_col = st.columns(2)
                    
                    with p_col:
                        if item.get("pros_evidence"):
                            st.markdown("**👍 Positive Points:**")
                            for p in item["pros_evidence"]:
                                st.write(f"- {p}")
                        elif cat == "Pro":
                            st.write("*No specific text evidence found.*")

                    with c_col:
                        if item.get("cons_evidence"):
                            st.markdown("**👎 Criticisms:**")
                            for c in item["cons_evidence"]:
                                st.write(f"- {c}")
                        elif cat == "Con":
                            st.write("*No specific text evidence found.*")
                    
                    if item.get("reference_evidence"):
                        st.markdown("---")
                        st.markdown("**ℹ️ Reference Points:**")
                        for r in item["reference_evidence"]:
                            st.write(f"- {r}")


