import streamlit as st
import requests

# Set page configuration
st.set_page_config(page_title="Product Insights", layout="wide")

# Backend Gateway Address
API_BASE_URL = "http://localhost:8001"

# Custom Styling
st.markdown("""
    <style>
    .stExpander { border: 1px solid #e6e9ef; border-radius: 8px; margin-bottom: 10px; }
    .stAlert { border-radius: 8px; }
    </style>
""", unsafe_allow_html=True)

# Helper function to fetch products
@st.cache_data(ttl=600) # Cache for 10 minutes
def get_all_products():
    try:
        response = requests.get(f"{API_BASE_URL}/products", timeout=5)
        if response.status_code == 200:
            return response.json().get("products", [])
    except:
        return []
    return []

st.title("Product Review Analysis")
st.divider()

# 1. Dynamically Load Product Options
all_products = get_all_products()

if not all_products:
    st.warning("⚠️ Could not load product list. Ensure the Gateway API is running.")
    # Fallback to manual entry if API is down
    item_id = st.text_input("Enter Product ID manually:")
else:
    selected_item = st.selectbox(
        "Search Product Database:",
        options=all_products,
        index=None,
        placeholder="Type or select a product ID...",
    )
    item_id = selected_item

# --- MAIN ANALYSIS LOGIC ---
if item_id:
    # --- FETCH DATA ---
    with st.spinner(f"Querying backend for {item_id}..."):
        try:
            response = requests.get(f"{API_BASE_URL}/items/{item_id}", timeout=60)
            if response.status_code == 200:
                data = response.json()
            else:
                st.error(f"Backend returned error {response.status_code}")
                st.stop()
        except:
            st.error("Could not connect to backend server.")
            st.stop()

    # --- RENDER DATA ---
    if data.get("status") == "INSUFFICIENT_DATA":
        st.warning(data.get('message'))
    else:
        left_col, right_col = st.columns([1, 2], gap="large")

        with left_col:
            st.subheader("Product Identity")
            st.markdown(f"**ID:** `{item_id}`")
            st.subheader("Executive Summary")
            st.info(data.get("summary", "No summary available."))
            st.caption("Generated by RAG Insights Engine v1.0")

        with right_col:
            st.subheader("Insights by Aspect")
            aspects = data.get("top_aspects", [])
            for item in aspects:
                cat = item.get("category", "Mixed")
                label = cat if cat != "Insufficient Data" else "Insufficient Data"

                with st.expander(f"{item['aspect']} ({label})"):
                    if cat == "Pro": st.success("Positive Sentiment Pattern")
                    elif cat == "Con": st.error("Negative Sentiment Pattern")
                    elif cat == "Mixed": st.warning("Mixed or Neutral Sentiment Pattern")
                    else: st.info("Insufficient Data for Sentiment Categorization")

                    p_col, c_col = st.columns(2)
                    with p_col:
                        if item.get("pros_evidence"):
                            st.markdown("**Positive Points:**")
                            for p in item["pros_evidence"]: st.write(f"- {p}")
                    with c_col:
                        if item.get("cons_evidence"):
                            st.markdown("**Criticisms:**")
                            for c in item["cons_evidence"]: st.write(f"- {c}")
                    
                    if item.get("reference_evidence"):
                        st.divider()
                        st.markdown("**Reference Points:**")
                        for r in item["reference_evidence"]: st.write(f"- {r}")
else:
    st.info("Please select a product from the searchable dropdown above to view its analysis.")
